services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - mydb
    ports:
      - "8088:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./:/mnt/extra-addons/
      - ${ENTERPRISE_PATH}:/mnt/enterprise-addons
    command: odoo --dev all,xml,reload -s
    restart: always
  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: