from . import res_partner
from . import producteca_account
from . import res_company
from . import producteca_connections
from . import producteca_queue
from . import product_product
from . import product_template
from . import stock_quant
from . import stock_warehouse
from . import sale_order
from . import stock_picking