from . import res_partner
from . import producteca_account
from . import res_company
from . import producteca_connections
from . import product_template
from . import product_product
from . import product_pricelist
from . import product_pricelist_item
from . import stock_quant
from . import stock_warehouse
from . import sale_order
from . import sale_order_cart
from . import stock_picking
from . import account_move
from . import account_journal
from . import account_payment